apiVersion: v1
kind: Secret
metadata:
  name: controlplane-secret
  namespace: controlplane
type: Opaque
stringData:
  JWT_ACCESS_SECRET: change-me-min-32-characters-long-x
  JWT_REFRESH_SECRET: change-me-min-32-characters-long-x
  DATABASE_URL: postgres://user:password@postgres-service:5432/controlplane
  REDIS_URL: redis://redis-service:6379
