// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auditlog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (organization_id, user_id, action, metadata)
VALUES ($1, $2, $3, $4)
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Action         string      `json:"action"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.OrganizationID,
		arg.UserID,
		arg.Action,
		arg.Metadata,
	)
	return err
}
