// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
	"encoding/json"
)

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, limits, created_at FROM plans WHERE name = $1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Limits,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPlan = `-- name: UpsertPlan :exec
INSERT INTO plans (name, limits)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
`

type UpsertPlanParams struct {
	Name   string          `json:"name"`
	Limits json.RawMessage `json:"limits"`
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) error {
	_, err := q.db.Exec(ctx, upsertPlan, arg.Name, arg.Limits)
	return err
}
