// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getOrgSubscriptionWithPlan = `-- name: GetOrgSubscriptionWithPlan :one
SELECT s.custom_limits, p.limits AS plan_limits
FROM org_subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.organization_id = $1
`

type GetOrgSubscriptionWithPlanRow struct {
	CustomLimits []byte          `json:"custom_limits"`
	PlanLimits   json.RawMessage `json:"plan_limits"`
}

func (q *Queries) GetOrgSubscriptionWithPlan(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionWithPlanRow, error) {
	row := q.db.QueryRow(ctx, getOrgSubscriptionWithPlan, organizationID)
	var i GetOrgSubscriptionWithPlanRow
	err := row.Scan(&i.CustomLimits, &i.PlanLimits)
	return i, err
}
